documentation doxygen

diff --git a/docs/doxygen/latex/Makefile b/docs/doxygen/latex/Makefile
--- a/docs/doxygen/latex/Makefile
+++ b/docs/doxygen/latex/Makefile
@@ -22,7 +22,11 @@ $(MANUAL_FILE).pdf: $(MANUAL_FILE).ps
 
 $(MANUAL_FILE).dvi: clean $(MANUAL_FILE).tex doxygen.sty
 	echo "Running latex..."
-	$(LATEX_CMD) $(MANUAL_FILE).tex
+	$(LATEX_CMD) $(MANUAL_FILE).tex || \
+	if [ $$? != 0 ] ; then \
+	        \echo "Please consult $(MANUAL_FILE).log to see the error messages" ; \
+	        false; \
+	fi
 	echo "Running makeindex..."
 	$(MKIDX_CMD) $(MANUAL_FILE).idx
 	echo "Rerunning latex...."
@@ -32,11 +36,19 @@ $(MANUAL_FILE).dvi: clean $(MANUAL_FILE).tex doxygen.sty
 	    do \
 	      echo "Rerunning latex...." ;\
 	      $(LATEX_CMD) $(MANUAL_FILE).tex ; \
+	      $(LATEX_CMD) $(MANUAL_FILE).tex || \
+	      if [ $$? != 0 ] ; then \
+	              \echo "Please consult $(MANUAL_FILE).log to see the error messages" ; \
+	              false; \
+	      fi; \
 	      latex_count=`expr $$latex_count - 1` ;\
 	    done
 	$(MKIDX_CMD) $(MANUAL_FILE).idx
-	$(LATEX_CMD) $(MANUAL_FILE).tex
-
+	$(LATEX_CMD) $(MANUAL_FILE).tex || \
+	if [ $$? != 0 ] ; then \
+	        \echo "Please consult $(MANUAL_FILE).log to see the error messages" ; \
+	        false; \
+	fi
 $(MANUAL_FILE).ps: $(MANUAL_FILE).ps
 	psnup -2 $(MANUAL_FILE).ps >$(MANUAL_FILE).ps
 
